<?php
    define('SQL_HOST','mysql');
    define('DB_HOST','sql9.freemysqlhosting.net');
    define('DB_NAME','sql9238008');
    define('DB_USER_NAME','sql9238008');
    define('DB_PASSWORD','qKpYXVmkCl');
    define('POST_NUMBER','3306');
    define('‘HTTP_HOST’',$_SERVER[‘HTTP_HOST’]);
?>